name: ipcidr
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 04 * * FRI"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Set requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set timezone to WIB Jakarta
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"

      - name: Install dnsutils
        run: sudo apt -y update && sudo apt install -y dnsutils

      - name: getDomainDoH
        run: |
          bash getDomainDOH.sh

      - name: resolveDOH
        run: |
          python3 resolveDOH.py

      - name: Set variables
        run: |
          echo "IP4=https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv4.txt" >> $GITHUB_ENV
          echo "IP6=https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv6.txt" >> $GITHUB_ENV
          echo "IPS=https://raw.githubusercontent.com/hagezi/dns-blocklists/main/ips/doh.txt" >> $GITHUB_ENV
        shell: bash

      # get from upstream
      - name: Get Lists IPs DNS
        run: |
          curl -sSL $IP4 | grep -Po '[^ ]*' | grep -E "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" > ipv4.tmp
          curl -sSL $IP6 | grep -Po '[^ ]*' | grep -E "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))" > ipv6.tmp
          curl -sSL $IPS | grep -Po '[^ ]*' | grep -E "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" > ips.tmp
          cat ipv4-doh.txt | grep -Po '[^ ]*' | grep -E "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" > ipv4-doh.tmp
          cat ipv6-doh.txt | grep -Po '[^ ]*' | grep -E "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))" > ipv6-doh.tmp

      # Parsing IP only
      - name: Merge IPv4 and IPv6
        run: |
          cat ipv4.tmp ipv4-doh.tmp ips.tmp | sort -u > ipv4.txt
          cat ipv6.tmp ipv6-doh.tmp | sort -u > ipv6.txt
          cat ipv4.txt ipv6.txt > ip-dns.txt

      # # Remove IPs CDN Cloudflare
      # - name: Filter No CDN
      #   run: |
      #     python3 filter.py

      # Commit changed files to your repo
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          # Commit message
          commit_message: automatic/regular IP-DNS updates
          # File pattern used for `git add`. For example `src/*.js`
          file_pattern: './ip*.txt *doh.txt'